name: 'GENERATE:RANDOM:PASSWORD'
description: 'Generates a random password and saves it as an artifact.'
author: 'Grant Zukel'
inputs:
  length:
    description: 'The length of the random password.'
    required: true
    default: 16
runs:
  using: 'composite'
  steps:
    - name: "GENERATE:PASSWORD"
      id: generate-password
      run: |
        LENGTH=${{ inputs.length }}
        PASSWORD=$(< /dev/urandom tr -dc 'A-Za-z0-9!@#$%^&*()_+' | head -c $LENGTH)
        echo "Generated password: $PASSWORD"
        echo "RANDOM_PASSWORD=$PASSWORD" >> $GITHUB_ENV
        echo $PASSWORD > random_password.txt

    - name: "UPLOAD:ARTIFACT"
      uses: actions/upload-artifact@v2
      with:
        name: random-password
        path: random_password.txt
