name: 'CALCULATE:AVERAGE:NETWORK:BLOCKTIME'
description: 'This composite is used for calculating average block time of a cosmos sdk network using the rpc url.'
inputs:
  avg_time_sample_size:
    description: "The sample size of blocks you want to calculate your average over."
    default: "10"
    required: false
  rpc_url:
    description: "the cosmosSDK RPC URL you want to use."
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: gzukel/CosmosComposites
        path: CosmosComposites

    - uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.10'

    - name: "REQUIREMENTS:INSTALL"
      shell: bash
      working-directory: "CosmosComposites/average_network_blocktime/"
      run: |
        pip install -r requirements.txt

    - name: "EXECUTE:CALCULATION"
      shell: bash
      working-directory: "CosmosComposites/average_network_blocktime/"
      env:
        AVG_TIME_SAMPLE_SIZE: "${{ inputs.avg_time_sample_size }}"
        RPC_URL: "${{ inputs.rpc_url }}"
      run: |
        python calculate_average_block_time_to_environment_var.py

